### ISSUE TITLE
Inquiring about the release of code

### ISSUE THREAD

**Issue by cyinen** [faceeyes/M3DFEL#1]
Hello! I am  interesting in your work.

Could you kindly inform me if there are plans to release new code for the repository this year? If so, could you provide any tentative timelines or insights into what features or improvements might be included?

Thank you for your dedication and hard work.

Looking forward to your response.

Best regards

**Comment by faceeyes** [comment]
Hi! 目前来说代码没有更新的打算，应该会固定为目前在腾讯TFace仓库中开源的的这个版本啦。

**Comment by cyinen** [comment]
> Hi! 目前来说代码没有更新的打算，应该会固定为目前在腾讯TFace仓库中开源的的这个版本啦。

可以给一个 链接吗，感谢

**Comment by faceeyes** [comment]
诶，点开readme里的链接就是呀，是遇到了什么问题吗？
